/*
 * Timer0Cfg.h
 *
 * Created: 3/25/2023 1:20:57 PM
 *  Author: Muhammed El Nabawy
 */ 


#ifndef TIMER0CFG_H_
#define TIMER0CFG_H_

/*
 *  Choose Timer0_mode:
 *	1- TIMER0_NORMAL_MODE
 *  2- TIMER0_CTC_MODE
 *  3- TIMER0_FAST_PWM_MODE
 *  4- TIMER0_PHASE_CORRECT_MODE
 */
#define TIMER0_MODE				TIMER0_FAST_PWM_MODE
//#define TIMER0_OC0_MODE			TIMER0_NORMAL_MODE
/*
 *  Choose Timer0_PRESCALLER:
 *	__NO_CLOCK_SOURCE__
 *	__NO_PRESCALLER__
 *  __TIMER0_PRESCALLER_8__
 *  __TIMER0_PRESCALLER_64__
 *  __TIMER0_PRESCALLER_256__
 *  __TIMER0_PRESCALLER_1024__
 *	__EXTERNAL_CLK_SOURCE_FALLIN_EDGE__
 *	__EXTERNAL_CLK_SOURCE_RISING_EDGE__               
 */
#define __TIMER0_PRESCALLER__		__TIMER0_PRESCALLER_256__
/*
 *  Choose Timer0_OC0_MODE:
 *	__TIMER0_OC0_MODE_DISCONNECTED__
 *	__TIMER0_OC0_MODE_TOGGLE__
 *  __TIMER0_OC0_MODE_CLEAR__
 *  __TIMER0_OC0_MODE_SET__ 
 *  NOTE: THIS OC0 MODES, IF TIMER0 ON NORMAL MODE OR CTC MODE
 *
 *  __TIMER0_OC0_MODE_DISCONNECTED__
 *	__TIMER0_OC0_MODE_NON_INVERTING_FAST_PWM__ 
 *  __TIMER0_OC0_MODE_INVERTING_FAST_PWM__
 *  NOTE: this is for fast pulse width modulation 
 *
 *	__TIMER0_OC0_MODE_DISCONNECTED__
 *  __TIMER0_OC0_MODE_NON_INVERTING_PHASE_CORRECT__
 *  __TIMER0_OC0_MODE_INVERTING_PHASE_CORRECT__
 *	NOTE: this is for PHASE CORRECT PWM 
 */	     
#define __TIMER0_OC0A_MODE__		__TIMER0_OC0_MODE_NON_INVERTING_FAST_PWM__
#define __TIMER0_OC0B_MODE__		__TIMER0_OC0_MODE_NON_INVERTING_FAST_PWM__






#endif /* TIMER0CFG_H_ */